# Generated by Django 3.0.2 on 2020-01-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
