# Generated by Django 3.0.2 on 2020-01-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200112_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_dates',
        ),
    ]
