# Generated by Django 3.0.2 on 2020-01-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_id',
        ),
    ]
